### ISSUE TITLE
How to run OpenGraphGym without horovod

### ISSUE THREAD

**Issue by AditiTripathi2019** [wz26/OpenGraphGym#1]
Hi,
I am working on steiner tree problem using RL and trying to use your code. But I am running into problem with horovod package. I wanted to know if there is a way to run your code without having installed horovod. If you can provide very specific instructions on how to achieve this it would be very helpful. I am using python 3.5.2 in ubuntu 16.04 LTS.
Thanks.

**Comment by wz26** [comment]
Hi, actually, I am currently working on a new cleaner version that no longer needs horovod. As to this version, you can try to comment out the horovod related code in model.py and the other parts. My understanding is that Horovod is like an add-on for TensorFlow. The code should still work on a single GPU when you remove it.
